### ISSUE TITLE
System.MissingFieldException - Wrong GEOMETRY field name

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-maestro-api-samples#3]
I hope you can see the image... I have transferred some code to a new WinServer2019 and MG 3.1.2 server and matched the Maestro API ... we have a drill-down point selector (to find all objects under a click, not just the top one). But the Maestro API is throwing an exception, like it hasn't resolved the "GEOMETRY" field properly?

Any help appreciated - not sure if it needs a API fix?

![image](https://user-images.githubusercontent.com/22054739/132215149-a63d5aa3-defe-4984-b3e5-9a96f6075459.png)

**Comment by Crispin-at-Linknode** [comment]
... may have dropped this in the wrong place... it's the MapGuide.MaestroAPI (not SDK)

**Comment by jumpinjackie** [comment]
Yeah, this repo is more for sample code using the MaestroAPI

Issue moved here (https://github.com/jumpinjackie/mapguide-maestro/issues/99). Let's continue the discussion there.
